---
name: Python CI

  on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  jobs:
  test:
    runs-on: ubuntu-latest

    env:
       APP_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run:
          pip install pytest flake8

      - name: Show environment
        run: echo "Environment is $APP_ENV"

      - name: Lint code
        run: flake8 

      - name: Run tests
        run: pytest

      - name: Test secret
        env:
        DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
        run: echo "Secret is available"

      - name: Build application
        run:
          mkdir build
          cp app.py build/
          cp test_app.py build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-demo
          path: build/


   steps:
      - name: Deploy
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: ./deploy.sh
 
